"""add avatar to user remove logo from organizer

Revision ID: 21b35e0e20b1
Revises: dc44b3697826
Create Date: 2026-02-01 22:21:12.204188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b35e0e20b1'
down_revision = 'dc44b3697826'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizer', 'logo')
    op.add_column('users', sa.Column('avatar', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.add_column('organizer', sa.Column('logo', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###