"""Add used_by to organizer_invite

Revision ID: 30b6325ed6f6
Revises: ed602255de23
Create Date: 2026-02-22 23:03:07.769617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b6325ed6f6'
down_revision = 'ed602255de23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizer_invite', sa.Column('used_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organizer_invite', 'organizer', ['used_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizer_invite', type_='foreignkey')
    op.drop_column('organizer_invite', 'used_by_id')
    # ### end Alembic commands ###