"""initial

Revision ID: 33c8feeeb2fe
Revises: 
Create Date: 2025-12-20 21:40:58.154855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c8feeeb2fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_user',
    sa.Column('auth_user_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('auth_user_id')
    )
    op.create_table('organizer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organizer_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.Text(), nullable=False),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizer')
    op.drop_table('auth_user')
    op.drop_table('users')
    # ### end Alembic commands ###