"""add team formation fields

Revision ID: 3caa8e078929
Revises: 4c701ebb75b2
Create Date: 2025-12-30 19:43:07.021923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3caa8e078929'
down_revision = '4c701ebb75b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('team_formation_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('competitions', sa.Column('team_formation_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'team_formation_end')
    op.drop_column('competitions', 'team_formation_start')
    # ### end Alembic commands ###