"""competition

Revision ID: 4c701ebb75b2
Revises: f64b68e0b7f9
Create Date: 2025-12-25 23:48:50.471807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c701ebb75b2'
down_revision = 'f64b68e0b7f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('competition_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('competition_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('min_participants', sa.Integer(), nullable=False),
    sa.Column('domains', sa.ARRAY(sa.Enum('FRONTEND', 'MOBILE', 'BACKEND', 'AI', 'DEVOPS', name='domain', native_enum=False)), nullable=False),
    sa.Column('participant_type', sa.Enum('SCHOOLCHILD', 'STUDENT', 'ANY', name='participanttype', native_enum=False), nullable=False),
    sa.Column('format', sa.Enum('ONLINE', 'OFFLINE', 'HYBRID', name='competitionformat', native_enum=False), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('max_team_size', sa.Integer(), nullable=False),
    sa.Column('min_team_size', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competitions')
    # ### end Alembic commands ###