"""Make bio and experience_level nullable, add age column

Revision ID: 5448829ba76d
Revises: f2ee3be10256
Create Date: 2026-04-16 00:50:32.403219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5448829ba76d'
down_revision = 'f2ee3be10256'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('age', sa.Integer(), nullable=False))
    op.alter_column('participants', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('participants', 'experience_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'experience_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('participants', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('participants', 'age')
    # ### end Alembic commands ###