"""Add auto_accept to competitions

Revision ID: 75e3a5cde34b
Revises: 30b6325ed6f6
Create Date: 2026-03-14 22:38:02.965769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e3a5cde34b'
down_revision = '30b6325ed6f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('auto_accept', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'auto_accept')
    # ### end Alembic commands ###