"""Add participant

Revision ID: 91974e63fdd3
Revises: 75e3a5cde34b
Create Date: 2026-20-03 22:19:30

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91974e63fdd3'
down_revision = '75e3a5cde34b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'participants',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('full_name', sa.String(150), nullable=False),
        sa.Column('avatar_url', sa.Text(), nullable=True),
        sa.Column('bio', sa.Text(), nullable=False),
        sa.Column('experience_level', sa.String(), nullable=False),
        sa.Column('preferred_domains', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    )
    
    op.create_table(
        'participant_skills',
        sa.Column('participant_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(70), nullable=False),
        sa.Column('level', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('participant_id', 'name'),
        sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE')
    )
    
    op.create_table(
        'participant_contacts',
        sa.Column('participant_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(70), nullable=False),
        sa.Column('url', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('participant_id', 'title'),
        sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE')
    )

def downgrade() -> None:
    op.drop_table('participant_contacts')
    
    op.drop_table('participant_skills')
    
    op.drop_table('participants')
