"""remove competition_start and competition_end

Revision ID: a27e1b3e175e
Revises: 3caa8e078929
Create Date: 2025-12-31 20:46:34.319209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a27e1b3e175e'
down_revision = '3caa8e078929'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'competition_end')
    op.drop_column('competitions', 'competition_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('competition_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('competitions', sa.Column('competition_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###