"""Add participant_type to participants

Revision ID: f2ee3be10256
Revises: 2a9f8e3c1b7d
Create Date: 2026-04-15 01:39:16.074247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ee3be10256'
down_revision = '2a9f8e3c1b7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('participant_type', sa.Enum('SCHOOLCHILD', 'STUDENT', 'ANY', name='participanttype', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'participant_type')
    # ### end Alembic commands ###