"""add_unique_constraints_to_organizer

Revision ID: f64b68e0b7f9
Revises: 33c8feeeb2fe
Create Date: 2025-12-20 21:58:57.969400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64b68e0b7f9'
down_revision = '33c8feeeb2fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'organizer', ['contact_email'])
    op.create_unique_constraint(None, 'organizer', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizer', type_='unique')
    op.drop_constraint(None, 'organizer', type_='unique')
    # ### end Alembic commands ###