"""Shared constants for integration tests."""

USER_ID = "1"
DIFFERENT_USER_ID = "2"
ADMIN_USER_ID = "3"
SUPERUSER_ID = "4"
PARTICIPANT_USER_ID = "5"
ANOTHER_PARTICIPANT_USER_ID = "6"

SUPERUSER_PASSWORD = "asd123321"  # noqa: S105
