services:
    tests:
        restart: no
        build:
            context: ../
            dockerfile: docker/tests.Dockerfile
        env_file:
            - "../.config/.env.tests"
        volumes:
            - "../.config/config.toml:/etc/dreamteams/config.toml"
        container_name: tests
        environment:
            - API_URL=http://api:${APP_SERVER_PORT}
        depends_on:
            - api
            - redis

    migrations:
        extends:
            file: docker-compose.base.yml
            service: migrations
        depends_on:
            db:
                condition: service_healthy

    api:
        extends:
            file: docker-compose.base.yml
            service: api
        depends_on:
            db:
                condition: service_healthy
            migrations:
                condition: service_completed_successfully
            rustfs:
                condition: service_started
            redis:
                condition: service_healthy
        environment:
            - APP_S3_PUBLIC_URL=http://rustfs:9000
            - APP_DB_HOST=db
            - APP_DB_PORT=5432

    db:
        extends:
            file: docker-compose.base.yml
            service: db

    redis:
        extends:
            file: docker-compose.base.yml
            service: redis

    rustfs:
        extends:
            file: docker-compose.base.yml
            service: rustfs