services:
    nginx:
        extends:
            file: docker-compose.base.yml
            service: nginx
        depends_on:
            api:
                condition: service_healthy
            oauth2-proxy:
                condition: service_healthy
            rustfs:
                condition: service_started
        networks:
            - "shared"

    oauth2-proxy:
        extends:
            file: docker-compose.base.yml
            service: oauth2-proxy
        depends_on:
            redis:
                condition: service_healthy
        networks:
            - "shared"

    redis:
        extends:
            file: docker-compose.base.yml
            service: redis
        volumes:
            - redis_data:/data
        networks:
            - "shared"

    migrations:
        extends:
            file: docker-compose.base.yml
            service: migrations
        depends_on:
            db:
                condition: service_healthy
        networks:
            - "shared"

    api:
        extends:
            file: docker-compose.base.yml
            service: api
        depends_on:
            pgbouncer:
                condition: service_started
            migrations:
                condition: service_completed_successfully
            rustfs:
                condition: service_started
        networks:
            - "shared"

    db:
        extends:
            file: docker-compose.base.yml
            service: db
        volumes:
            - pg_data:/var/lib/postgresql
        networks:
            - "shared"

    pgbouncer:
        extends:
            file: docker-compose.base.yml
            service: pgbouncer
        depends_on:
            db:
                condition: service_healthy
        networks:
            - "shared"

    rustfs:
        extends:
            file: docker-compose.base.yml
            service: rustfs
        volumes:
            - rustfs_data:/data
        networks:
            - "shared"

volumes:
    pg_data:
    grafana_data:
    loki_data:
    redis_data:
    rustfs_data:

networks:
    shared:
        external: true
