"""Competition-specific input limits for request validation."""

MAX_COMPETITION_TRACKS = 30
MAX_COMPETITION_MILESTONES = 30
MAX_COMPETITION_DESCRIPTION_LENGTH = 10_000
MAX_PARTICIPANTS = 100_000
MAX_TEAM_SIZE = 1_000
MAX_LOCATION_LENGTH = 500
