"""remove unused uq_auth_user constraint

Revision ID: 3e26fb99b211
Revises: 6b18d744300b
Create Date: 2025-12-14 13:13:18.159246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e26fb99b211'
down_revision = '6b18d744300b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_auth_user'), 'auth_user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_auth_user'), 'auth_user', ['user_id', 'auth_user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###