"""remove landlord_id field from user

Revision ID: 7536e5a83a1e
Revises: ff14924c9daf
Create Date: 2025-12-19 00:05:06.338666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7536e5a83a1e'
down_revision = 'ff14924c9daf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_landlord_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'landlord_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('landlord_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_landlord_id_fkey'), 'users', 'landlord', ['landlord_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###