"""landlord

Revision ID: 8a409cc9fd9e
Revises: 3e26fb99b211
Create Date: 2025-12-16 15:07:00.869412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a409cc9fd9e'
down_revision = '3e26fb99b211'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###