"""add contact_email field to landlord

Revision ID: 984af121f9fa
Revises: bf9b9c035b3d
Create Date: 2025-12-18 23:28:53.909362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984af121f9fa'
down_revision = 'bf9b9c035b3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlord', sa.Column('contact_email', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landlord', 'contact_email')
    # ### end Alembic commands ###