"""add avatar field to user

Revision ID: ad1c72e01d92
Revises: 7536e5a83a1e
Create Date: 2025-12-19 00:11:07.000326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1c72e01d92'
down_revision = '7536e5a83a1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlord', sa.Column('avatar', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landlord', 'avatar')
    # ### end Alembic commands ###