"""add landlord

Revision ID: bf9b9c035b3d
Revises: 8a409cc9fd9e
Create Date: 2025-12-16 15:08:46.069247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9b9c035b3d'
down_revision = '8a409cc9fd9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlord',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('landlord_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landlord')
    # ### end Alembic commands ###