"""add landlord_id field to user

Revision ID: ff14924c9daf
Revises: 984af121f9fa
Create Date: 2025-12-18 23:58:43.108863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff14924c9daf'
down_revision = '984af121f9fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('landlord_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'landlord', ['landlord_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'landlord_id')
    # ### end Alembic commands ###