[auth]
user_id_header = "X-Auth-User"
user_email_header = "X-Auth-User-Email"
access_token_header = "X-Access-Token"
access_token_alg = "RS256"
allow_unverified_email = true

[otel]
endpoint = "http://otel-collector:4318"
service_name = "dreamteams"
sample_ratio = 0.1
metric_export_interval_ms = 10000

[cors]
allow_origins = ["http://localhost:3001"]
allow_credentials=true
allow_methods=["*"]
allow_headers=["*"]

[api]
root_path = "/api"