[auth]
user_id_header = "X-Auth-User"
user_email_header = "X-Auth-User-Email"
access_token_header = "X-Access-Token"
access_token_alg = "RS256"
allow_unverified_email = true

[otel]
endpoint = "http://tempo:4318/v1/traces"
service_name = "dreamteams"

[cors]
allow_origins = ["http://localhost:3001"]
allow_credentials=true
allow_methods=["*"]
allow_headers=["*"]

[api]
root_path = "/api"